Algoritmo "EX10_GRAUS_FAHRENHEIT"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : SADINGANI SOFRIMENTO
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : NZOLA KIAMPAVA
// Data atual  : 13/10/2023
Var
// Seção de Declarações das variáveis 
   C, F : REAL


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   LEIA(F)
   
   C <- (5*(F-32))/9
   
   ESCREVAL(C)


Fimalgoritmo