Algoritmo "antecessor_sucessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/10/2023
Var
// Seção de Declarações das variáveis 
   n : INTEIRO

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   LEIA(N)
   
   ESCREVAL("sEU ANTECESSOR: ", N-1)
   ESCREVAL("SEU SUCESSOR: ", N+1)

Fimalgoritmo